.development_template: &developmentCD
  before_script:
    - npm ci --cache .npm --prefer-offline
  only:
    refs:
      - /^master$/

coverage-report:
  <<: *developmentCD
  stage: test
  script:
    - npm run coverage
  artifacts:
    paths:
      - coverage
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
