.merge_request_template: &mergeRequestCI
  before_script:
    - npm ci --cache .npm --prefer-offline
  only:
    refs:
      - merge_requests

lint:
  <<: *mergeRequestCI
  stage: test
  script:
    - npm run lint

typescript:
  <<: *mergeRequestCI
  stage: test
  script:
    - npm run build

tests-coverage:
  <<: *mergeRequestCI
  stage: test
  script:
    - CI=true npm run coverage
  artifacts:
    paths:
      - coverage
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
